config/routes.rb
Rails.application.routes.draw do
  resources :contacts, only: [:new, :create]
  root 'home#index'
  get 'thank-you', to: 'contacts#thanks'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contact.rb
class Contact < ApplicationRecord
  # validates :name, presence: true
  # validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: %i[edit]

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts or /contacts.json
  def create
    contact = Contact.new(contact_params)

    if contact.save
      ContactMailer.welcome_email.deliver_now
      redirect_to thank_you_path()
    else
      flash[:error] = "Contact was not created."
    end
  end

  def thanks
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def contact_params
      params.require(:contact).permit(:name, :email, :phone, :message)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/contacts/_contact.html.erb
<div id="<%= dom_id contact %>">
  <p>
    <strong>Name:</strong>
    <%= contact.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= contact.email %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= contact.phone %>
  </p>

  <p>
    <strong>Message:</strong>
    <%= contact.message %>
  </p>

</div>

app/views/contacts/_form.html.erb
<%= form_with(model: contact) do |form| %>
  <div id="form-group">
    <%= form.label :name, "Name & Surname", style: "display: block" %>
    <%= form.text_field :name, placeholder: "Who are you?", required: true %>
  </div>
  <div id="form-group">
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email, placeholder: "How we can talk to you?", required: true %>
  </div>
  <div id="form-group">
    <%= form.label :phone, "Phone Number", style: "display: block" %>
    <%= form.text_field :phone, placeholder: "Where can we reach you?" %>
  </div>
  <div id="form-group">
    <%= form.label :message, "Your message", style: "display: block" %>
    <%= form.text_area :message, placeholder: "Type your message here" %>
  </div>
  <div id="form-action">
    <p> We'll get back to you as soon as possible. </p>
    <%= form.submit "Send Message" %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing contact</h1>

<%= render "form", contact: @contact %>

<br>

<div>
  <%= link_to "Show this contact", @contact %> |
  <%= link_to "Back to contacts", contacts_path %>
</div>

app/views/contacts/new.html.erb
<div id="container">
  <div id="left-section">
    <img
      src="https://nurturing-potential-website.s3.ap-south-1.amazonaws.com/images/HealthyTalk-VickiTurner.jpg"
      alt="contact us"
    />
  </div>
  <div id="right-section">
    <h1>Don't be shy, get in touch!</h1>
    <%= render "form", contact: @contact %>
  </div>
</div>


<section id="contact-details-section">
  <div id="contact-details">
    <div id="headings">
      <h1 id="contact-heading"
      >Want to talk to us <span>direct?</span></h1>
      <h1 id="contact-subheading">No Problem!</h1>
    </div>
    <div id="detail-sections">
      <div id="phone">
        <h2>Call us</h2>
        <p>Give us a call - always happy to talk to you!</p>
        <a href="tel:+447448627775" id="phone-number">+44 1234 567890
          <span id="arrow">
            <%= image_tag("icons8-arrow-50-black.png", alt: "arrow") %>      
            <div id="orange">
            </div>
          </span>
        </a>
      </div>
      <div id="phone">
        <h2>Text us</h2>
        <p>Reach out via WhatsApp - we're here to chat!</p>
         <a href="https://wa.me/+447448627775?text=Hello%2C%20I%20have%20a%20question%20about%20your%20courses%20and%20learning%20resources." target="_blank" id="phone-number">+44 1234 567890
          <span id="arrow">
            <%= image_tag("icons8-arrow-50-black.png", alt: "arrow") %>      
            <div id="orange">
            </div>
          </span>
         </a>
      </div>
      <div id="email">
        <h2>Email us</h2>
        <p>Drop us an note - we'll get back to you asap!</p>
        <a id="email-address" href="mailto:hello@priyanka.co.uk" >hello@priyanka.co.uk
          <span id="arrow">
            <%= image_tag("icons8-arrow-50-black.png", alt: "arrow") %>    
            <div id="orange">
            </div>
          </span>
        </a>
      </div>
    </div>
  </div>
</section>

<script>
  gsap.from("#left-section img", {
    duration: 2,
    y: 100,
    opacity: 0,
    ease: "power2.out",
  });

  gsap.from("#headings h1", {
    duration: 2,
    y: 100,
    opacity: 0,
    ease: "power2.out",
    scrollTrigger: {
      trigger: "#headings",
      start: "top 80%",
    },
  });

  gsap.from("#detail-sections div", {
    duration: 2,
    y: 100,
    opacity: 0,
    ease: "power2.out",
    scrollTrigger: {
      trigger: "#detail-sections",
      start: "top 80%",
    },
  });
</script>

app/views/contacts/thanks.html.erb
<div id="container">
  <div id="left-section">
    <img
      src="https://nurturing-potential-website.s3.ap-south-1.amazonaws.com/images/thank-you.jpeg"
      alt="contact us"
    />
  </div>
  <div id="right-section">
    <h1>Thank you for your enquiry</h1>
    <p>We'll get back to you as soon as possible.</p>
    <a href="/" id="back-home"
    >Back to Home
      <span id="arrow">
        <%= image_tag("icons8-arrow-50-black.png", alt: "arrow") %>
        <div id="orange">
        </div>
      </span>
    </a>
  </div>
</div>

<section id="contact-details-section">
  <div id="contact-details">
    <div id="headings">
      <h1 id="contact-heading"
      >Want to talk to us <span>direct?</span></h1>
      <h1 id="contact-subheading">No Problem!</h1>
    </div>
    <div id="detail-sections">
      <div id="phone">
        <h2>Call us</h2>
        <p>Give us a call - always happy to talk to you!</p>
        <a href="tel:+447448627775" id="phone-number">+44 1234 567890
          <span id="arrow">
            <%= image_tag("icons8-arrow-50-black.png", alt: "arrow") %>      
            <div id="orange">
            </div>
          </span>
        </a>
      </div>
      <div id="phone">
        <h2>Text us</h2>
        <p>Reach out via WhatsApp - we're here to chat!</p>
         <a href="https://wa.me/+447448627775?text=Hello%2C%20I%20have%20a%20question%20about%20your%20courses%20and%20learning%20resources." target="_blank" id="phone-number">+44 1234 567890
          <span id="arrow">
            <%= image_tag("icons8-arrow-50-black.png", alt: "arrow") %>      
            <div id="orange">
            </div>
          </span>
         </a>
      </div>
      <div id="email">
        <h2>Email us</h2>
        <p>Drop us an note - we'll get back to you asap!</p>
        <a id="email-address" href="mailto:hello@priyanka.co.uk" >hello@priyanka.co.uk
          <span id="arrow">
            <%= image_tag("icons8-arrow-50-black.png", alt: "arrow") %>    
            <div id="orange">
            </div>
          </span>
        </a>
      </div>
    </div>
  </div>
</section>

<script>
  gsap.from("#left-section img", {
    duration: 2,
    y: 100,
    opacity: 0,
    ease: "power2.out",
  });

  gsap.from("#headings h1", {
    duration: 2,
    y: 100,
    opacity: 0,
    ease: "power2.out",
    scrollTrigger: {
      trigger: "#headings",
      start: "top 80%",
    },
  });

  gsap.from("#detail-sections div", {
    duration: 2,
    y: 100,
    opacity: 0,
    ease: "power2.out",
    scrollTrigger: {
      trigger: "#detail-sections",
      start: "top 80%",
    },
  });
</script>

app/views/home/index.html.erb
<section id="page1">
  <h1 id="heading1"> Empowering Growth & Learning </h1>
  <img src="https://nurturing-potential-website.s3.ap-south-1.amazonaws.com/images/img1.jpg" alt="img2" id="img1">
  <img src="https://nurturing-potential-website.s3.ap-south-1.amazonaws.com/images/tinkle_cover.jpeg" alt="img1" id="img2">
</section>
<section id="page2">
  <h5>
    At Nurturing Potential Limited,
  </h5>
  <h1>
    our mission is to help every person
    reach their <span> full potential</span>.
    <br>
    We do this by offering personalized support and encouraging group sessions.
    <br>
    Our commitment is to be with you every step of the way, guiding you to success.
  </h1>
  <div id="about-us">
    <h4>About us</h4>
    <div id="greendiv">
      <%= image_tag("icons8-arrow-50.png", alt: "arrow") %>
    </div>
  </div>
</section>
<script>
  // Page 1 animations
  gsap.from("#img1", {duration: 2, x: -200, opacity: 0, scale: 0.5});
  gsap.from("#img2", {duration: 2, x: 200, opacity: 0, scale: 0.5});
  gsap.from("#page1 #heading1", {duration: 2, y: -200, opacity: 0, scale: 0.5});

  // Page 2 animations
  gsap.from("#page2 h5", {opacity: 0, duration: 2, scrollTrigger: {trigger: "#page2 h5", start: "top 80%"}})
</script>

app/views/layouts/_navbar.html.erb
<div id="nav">
  <a href="<%= root_path %>">
    <h1>Nurturing Potential Ltd</h1>
  </a>
  <div class="" id="part2">
    <a href="#" class="disabled-link">About us</a>
    <a href="#" class="disabled-link">Services</a>
    <a href="#" class="disabled-link">Pricing</a>
    <a href="#" class="disabled-link">FAQ</a>
    <a href="<%= new_contact_path %>" id="contact">
      <h5>
        Contact us
      </h5>
      <div id="orange">
      </div>
    </a>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NurturingPotentialWebsite</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=DM+Sans:ital,opsz,wght@0,9..40,100..1000;1,9..40,100..1000&display=swap" rel="stylesheet">
    <%= javascript_importmap_tags %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.5/gsap.min.js" integrity="sha512-7eHRwcbYkK4d9g/6tD/mhkf++eoTHwpNM9woBxtPUBWm67zeAfFC+HrdoE2GanKeocly/VxeLvIqwvCdk7qScg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.5/ScrollTrigger.min.js" integrity="sha512-onMTRKJBKz8M1TnqqDuGBlowlH0ohFzMXYRNebz+yOcc5TQr/zAKsthzhuv0hiyUKEiQEQXEynnXCvNTOk50dg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
  </head>
  <body>
    <div id="main">
      <%= render "layouts/navbar" %>
      <%= yield %>
    </div>
  </body>
</html>